[package]
name = "sozuctl"
description = "command line application to configure a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozuctl"
homepage = "http://sozu.io"
version = "0.4.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

[[bin]]
name = "sozuctl"

[dependencies]
clap    = "^2.19.0"
mio-uds = "^0.6"
rand    = "^0.3"
prettytable-rs = "^0.6"
sozu-command-lib = { version = "^0.4", path = "../command" }

[features]
unstable = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
